### ISSUE TITLE
pkl2sac creates sac files with incorrect header values

### ISSUE THREAD

**Issue by smlloyd** [pysmo/aimbat#107]
Converting back seems to assign arbitrary numbers for stla, stlo, and stel.

**Comment by Aicha-C** [comment]
After running aimbat-sac2pkl -p event_name and sac--->lh to verify the sachead info, the stla, stlo, and stel are assigned the same values for all the stations.
A colleague and I tried to fix the problem by adjusting the sacpickle.py code in the Aimbat package. Please find attached files to see the changes we made to the code. 
These adjustments seemed to have fixed the problem. We were able to have the correct stla, stlo, and stel for all the stations after the conversion.
However, we ran again into the same issue despite having made these changes that seemed to have worked only for some time.

A data file will be sent shortly to provide more details about the files we're using.

<img width="246" alt="Obj2" src="https://user-images.githubusercontent.com/88288624/127783243-3f7a3da8-c376-4f64-bdd6-bfdd2c9be4c0.PNG">
<img width="365" alt="Obj1" src="https://user-images.githubusercontent.com/88288624/127783244-0bb5d5c3-e29f-40b3-b9b6-8ca874b21301.PNG">
<img width="386" alt="Obj" src="https://user-images.githubusercontent.com/88288624/127783245-a93f3302-da33-49a0-813a-f190a1215c3a.PNG">

**Comment by Aicha-C** [comment]
The final code is up and the initial is down.

**Comment by smlloyd** [comment]
Thanks for this information @Aicha-C !

That second loop over saclist does look a bit redundant, doesn't it? I agree with removing it. I don't quite see why the other change you made (lines 341-342) would make a difference, however. I suspect the real cause for the incorrect header values lies somewhere else.

With that said, I actually plan on removing `SacDataHdrs` altogether. It was initially required because of limitations elsewhere (in `SacIO`). This should simplify the code a bit, and hopefully make this easier to fix. Perhaps you can send/attach 2 files that currently garble up the header fields, and I'll write a test for it when making changes to AIMBAT?

**Comment by Aicha-C** [comment]
[Pn_files.zip](https://github.com/pysmo/aimbat/files/6918862/Pn_files.zip)
Thank you, @smlloyd . 
Please find attached the zip file containing two regional events that have been processed with AIMBAT. Each event contains a tmp directory where the conversion from pkl to sac can be operated to avoid altering the original data.

**Comment by smlloyd** [comment]
> [Pn_files.zip](https://github.com/pysmo/aimbat/files/6918862/Pn_files.zip)
> Thank you, @smlloyd .
> Please find attached the zip file containing two regional events that have been processed with AIMBAT. Each event contains a tmp directory where the conversion from pkl to sac can be operated to avoid altering the original data.

Hi @Aicha-C ,

That loop was indeed the problem, as it caused evla, evlo, evel to be looked up for one station, but written to all stations. So the header values ended up being the same as the station used to look them up in the last iteration. The attached zip file is empty (maybe github doesn't allow uploading zip files?), but removing the loop works for me when testing on other files.

I made a new release (v1.0.6) with this fix in it. It can also be installed with pip (use the ``-U`` flag to upgrade)

-S

**Comment by Aicha-C** [comment]
Hello Dr. @smlloyd,

I was able to update AIMBAT from v1.0.5 to v1.0.7 instead of v1.0.6. However, the conversion worked and the headers were well written for every station. 

Thank you so much for your help,

@Aicha-C
